name: Java

on: [push,release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: skycore-1.0-SNAPSHOT-all.jar
        # Directory containing files to upload
        path: build/libs/
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/libs/skycore-1.0-SNAPSHOT-all.jar application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
